version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: ${PROJECT_NAME}_db
    restart: always
    volumes:
      - ./.docker/mongo:/data/db
    ports:
      - ${MONGO_PORT}:27017
